name: Release on tag

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    uses: tx-pts-dai/github-workflows/.github/workflows/gh-release.yaml@v0.22.0
    with:
      tag: ${{ github.ref_name }}
